# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d81a75a8ec23679034d9592a4ab8c65cf8fba3fa1ae804943f545ccf1094e9ace525a589026c5b46b3ca2c031d437693d818ff5cad8f7fa3ea6b7e6e843fda5a

test:
  secret_key_base: 67d751d4b0b8ecaee628db5a22ee99d546841259da0b07062c3eb8b9a782d396bbe9ac631e3568ef9513aba0a712b0755d770d1a21196156299fee4c668958e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
